(in-package :cl-info)
(let (
(deffn-defvr-pairs '(
; CONTENT: (<INDEX TOPIC> . (<FILENAME> <BYTE OFFSET> <LENGTH IN CHARACTERS> <NODE NAME>))
("farey" . ("padics.info" 13187 284 "Definitions for package padics"))
("hensel" . ("padics.info" 10068 519 "Definitions for package padics"))
("hensel_to_farey" . ("padics.info" 13472 565 "Definitions for package padics"))
("nicehensel" . ("padics.info" 10588 684 "Definitions for package padics"))
("normalize_hensel" . ("padics.info" 11273 280 "Definitions for package padics"))
("padic_backsub" . ("padics.info" 16126 920 "Definitions for package padics"))
("padic_canonical" . ("padics.info" 9086 423 "Definitions for package padics"))
("padic_distance" . ("padics.info" 9772 295 "Definitions for package padics"))
("padic_divide" . ("padics.info" 12726 460 "Definitions for package padics"))
("padic_gauss" . ("padics.info" 14899 1226 "Definitions for package padics"))
("padic_multiply" . ("padics.info" 12338 387 "Definitions for package padics"))
("padic_norm" . ("padics.info" 9510 261 "Definitions for package padics"))
("padic_order" . ("padics.info" 8866 219 "Definitions for package padics"))
("padic_sqrt" . ("padics.info" 14488 410 "Definitions for package padics"))
("padic_substract" . ("padics.info" 12046 291 "Definitions for package padics"))
("padic_sum" . ("padics.info" 11554 491 "Definitions for package padics"))
("sqrtmod" . ("padics.info" 14038 449 "Definitions for package padics"))
))
(section-pairs '(
; CONTENT: (<NODE NAME> . (<FILENAME> <BYTE OFFSET> <LENGTH IN CHARACTERS>))
("Definitions for package padics" . ("padics.info" 8796 8250))
("Introduction to package padics" . ("padics.info" 613 8038))
)))
(load-info-hashtables (maxima::maxima-load-pathname-directory) deffn-defvr-pairs section-pairs))
